language: php

sudo: true

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

  allow_failures:
    - php: hhvm

cache:
  directories:
    - laravel #only cache the laravel directory

services: mysql

install:
  # create a new database for the hyn connection
  - export DB_USERNAME=travis DB_DATABASE=hyn DB_PASSWORD= QUEUE_DRIVER=sync
  # specify the laravel service providers to insert
  - export PACKAGE_PROVIDER="
    PrateekKathal\\\\SimpleCurl\\\\SimpleCurlServiceProvider::class,
  #specify the package to test
  - export PACKAGE_NAME=prateekkathal/laravel-simplecurl
  #run the setup script
  - curl -s https://raw.githubusercontent.com/kevupton/docker-laravel-tests/master/setup.sh | bash

script:
  #script to setup the package for testing
  - cd laravel
  - composer update
  - phpunit "vendor/$PACKAGE_NAME" #runs the phpunit just for your package.
